import { IMoto } from "../types/moto";

export const moto_array: IMoto[] = [
  {
    marca: "Honda",
    modelo: "CBR600RR",
    año: 2020,
    cilindrada: 600,
    color: "Rojo",
    tipo: "deportiva",
    potencia: 113,
    peso: 186,
    transmision: "manual",
    precio: 11799,
    disponible: true,
    combustible: "gasolina",
    consumo: 5.6,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17.1,
    numeroMarchas: 6,
    alturaAsiento: 82,
    fechaIngreso: new Date("2023-05-10"),
    descripcion: "Moto deportiva con gran desempeño en pista y ciudad.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk_j9lXLf48GDrFPEN4lH_gR1sxkU1LXRLyA&s"
  },
  {
    marca: "Yamaha",
    modelo: "YZF-R1",
    año: 2021,
    cilindrada: 1000,
    color: "Azul",
    tipo: "deportiva",
    potencia: 200,
    peso: 200,
    transmision: "manual",
    precio: 17399,
    disponible: false,
    combustible: "gasolina",
    consumo: 6.3,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17,
    numeroMarchas: 6,
    alturaAsiento: 85,
    fechaIngreso: new Date("2023-01-15"),
    descripcion: "Deportiva de alta performance con tecnología avanzada.",
    imagenUrl: "https://p.turbosquid.com/ts-thumb/42/QlarDU/GNHSd7Ea/r1main/jpg/1088442748/600x600/fit_q87/e32a9b5e71b283985488c249f8baa18158607268/r1main.jpg"
  },
  {
    marca: "Kawasaki",
    modelo: "Ninja ZX-6R",
    año: 2019,
    cilindrada: 636,
    color: "Verde",
    tipo: "deportiva",
    potencia: 130,
    peso: 196,
    transmision: "manual",
    precio: 9999,
    disponible: true,
    combustible: "gasolina",
    consumo: 5.8,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17,
    numeroMarchas: 6,
    alturaAsiento: 83,
    fechaIngreso: new Date("2022-09-12"),
    descripcion: "Balance perfecta entre potencia y maniobrabilidad.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyAX5d1m8IoxWvhDqDvcXO69M_gteM57EeXQ&s"
  },
  {
    marca: "Ducati",
    modelo: "Panigale V2",
    año: 2022,
    cilindrada: 955,
    color: "Rojo",
    tipo: "deportiva",
    potencia: 155,
    peso: 200,
    transmision: "manual",
    precio: 16995,
    disponible: true,
    combustible: "gasolina",
    consumo: 6.0,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 16,
    numeroMarchas: 6,
    alturaAsiento: 84,
    fechaIngreso: new Date("2023-04-20"),
    descripcion: "Estilo italiano con gran rendimiento en pista.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcUbXp3c3fLpZznT5yRMLpIJS4W6J_hFoeXg&s"
  },
  {
    marca: "Suzuki",
    modelo: "GSX-R750",
    año: 2018,
    cilindrada: 750,
    color: "Azul",
    tipo: "deportiva",
    potencia: 148,
    peso: 187,
    transmision: "manual",
    precio: 11500,
    disponible: false,
    combustible: "gasolina",
    consumo: 5.7,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17,
    numeroMarchas: 6,
    alturaAsiento: 81,
    fechaIngreso: new Date("2021-11-05"),
    descripcion: "Potente y ligera para pilotos agresivos.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8wKhHQn4VLPvznCk6e5igC3c1myK0eN5r6A&s"
  },
  {
    marca: "BMW",
    modelo: "S1000RR",
    año: 2020,
    cilindrada: 999,
    color: "Blanco",
    tipo: "deportiva",
    potencia: 205,
    peso: 197,
    transmision: "manual",
    precio: 16900,
    disponible: true,
    combustible: "gasolina",
    consumo: 6.4,
    sistemaFrenos: "ABS Pro, discos delanteros y traseros",
    capacidadTanque: 17.5,
    numeroMarchas: 6,
    alturaAsiento: 82,
    fechaIngreso: new Date("2023-06-01"),
    descripcion: "Tecnología alemana para máxima velocidad.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEGVTJoqr2ZfLnOxGlqnpSOLSKXhP_zNv6yQ&s"
  },
  {
    marca: "Harley-Davidson",
    modelo: "Street 750",
    año: 2017,
    cilindrada: 749,
    color: "Negro",
    tipo: "cruiser",
    potencia: 53,
    peso: 223,
    transmision: "manual",
    precio: 7499,
    disponible: false,
    combustible: "gasolina",
    consumo: 6.8,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 13.1,
    numeroMarchas: 5,
    alturaAsiento: 74,
    fechaIngreso: new Date("2021-05-15"),
    descripcion: "Clásica urbana con estilo inconfundible.",
    imagenUrl: "https://www.motorcyclecruiser.com/resizer/h5V8PnfiofbiuwQg8BVGc0fTUxw=/arc-photo-octane/arc3-prod/public/77O26EBC5IAP26L3FPIXPVBZLY.jpg"
  },
  {
    marca: "Triumph",
    modelo: "Street Triple RS",
    año: 2021,
    cilindrada: 765,
    color: "Gris",
    tipo: "naked",
    potencia: 121,
    peso: 168,
    transmision: "manual",
    precio: 11600,
    disponible: true,
    combustible: "gasolina",
    consumo: 5.5,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17.4,
    numeroMarchas: 6,
    alturaAsiento: 83,
    fechaIngreso: new Date("2023-02-18"),
    descripcion: "Naked ágil para ciudad y carretera.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR525Y9fKV2JDl9ZPXpOsJumqNP6KpPfsMSMQ&s"
  },
  {
    marca: "KTM",
    modelo: "RC 390",
    año: 2021,
    cilindrada: 373,
    color: "Naranja",
    tipo: "deportiva",
    potencia: 44,
    peso: 172,
    transmision: "manual",
    precio: 5599,
    disponible: true,
    combustible: "gasolina",
    consumo: 3.7,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 10,
    numeroMarchas: 6,
    alturaAsiento: 82,
    fechaIngreso: new Date("2023-03-10"),
    descripcion: "Deportiva ligera para principiantes.",
    imagenUrl: "https://potenza.com.co/wp-content/uploads/2024/03/020820221659451904RC_390_NG_2022_BLUE_360_1-1.png"
  },
  {
    marca: "Honda",
    modelo: "CB500F",
    año: 2019,
    cilindrada: 471,
    color: "Negro",
    tipo: "naked",
    potencia: 47,
    peso: 189,
    transmision: "manual",
    precio: 6500,
    disponible: true,
    combustible: "gasolina",
    consumo: 4.5,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17.1,
    numeroMarchas: 6,
    alturaAsiento: 79,
    fechaIngreso: new Date("2022-08-08"),
    descripcion: "Moto versátil para uso diario.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNmmSX-D06aXV4KlG76bh-HL3j5fZvk0SBCg&s"
  },
  {
    marca: "Yamaha",
    modelo: "MT-07",
    año: 2020,
    cilindrada: 689,
    color: "Negro",
    tipo: "naked",
    potencia: 74,
    peso: 182,
    transmision: "manual",
    precio: 7600,
    disponible: true,
    combustible: "gasolina",
    consumo: 4.2,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 14,
    numeroMarchas: 6,
    alturaAsiento: 81,
    fechaIngreso: new Date("2022-12-12"),
    descripcion: "Moto naked con buen balance entre potencia y peso.",
    imagenUrl: "https://www.incolmotos-yamaha.com.co/wp-content/uploads/2019/05/AP002195909_2025_MTN690_MLNM4_EUR_360_001_03-35.jpg"
  },
  {
    marca: "Kawasaki",
    modelo: "Z900",
    año: 2019,
    cilindrada: 948,
    color: "Verde",
    tipo: "naked",
    potencia: 125,
    peso: 210,
    transmision: "manual",
    precio: 9500,
    disponible: false,
    combustible: "gasolina",
    consumo: 5.7,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 17,
    numeroMarchas: 6,
    alturaAsiento: 82,
    fechaIngreso: new Date("2021-10-10"),
    descripcion: "Naked potente y versátil.",
    imagenUrl: "https://auteco.vtexassets.com/arquivos/ids/1006386-800-auto?v=638871762330970000&width=800&height=auto&aspect=true"
  },
  {
    marca: "Ducati",
    modelo: "Monster 821",
    año: 2018,
    cilindrada: 821,
    color: "Rojo",
    tipo: "naked",
    potencia: 112,
    peso: 209,
    transmision: "manual",
    precio: 11300,
    disponible: true,
    combustible: "gasolina",
    consumo: 5.9,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 16,
    numeroMarchas: 6,
    alturaAsiento: 80,
    fechaIngreso: new Date("2022-05-05"),
    descripcion: "Estilo italiano con buen rendimiento.",
    imagenUrl: "https://ducatimadrid.com/wp-content/uploads/2025/04/MODELOS-lateral-6.png.webp"
  },
  {
    marca: "Suzuki",
    modelo: "V-Strom 650",
    año: 2021,
    cilindrada: 645,
    color: "Amarillo",
    tipo: "adventure",
    potencia: 70,
    peso: 213,
    transmision: "manual",
    precio: 8300,
    disponible: true,
    combustible: "gasolina",
    consumo: 4.8,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 20,
    numeroMarchas: 6,
    alturaAsiento: 85,
    fechaIngreso: new Date("2023-01-10"),
    descripcion: "Ideal para viajes largos y terrenos variados.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNoqjdoljN7o8hxi7p6v56oyxkf8pBs8zbNA&s"
  },
  {
    marca: "BMW",
    modelo: "R1250GS",
    año: 2022,
    cilindrada: 1254,
    color: "Blanco",
    tipo: "adventure",
    potencia: 136,
    peso: 249,
    transmision: "manual",
    precio: 17800,
    disponible: false,
    combustible: "gasolina",
    consumo: 5.1,
    sistemaFrenos: "ABS Pro, discos delanteros y traseros",
    capacidadTanque: 20,
    numeroMarchas: 6,
    alturaAsiento: 85,
    fechaIngreso: new Date("2023-04-01"),
    descripcion: "Máquina todoterreno con tecnología de punta.",
    imagenUrl: "https://www.lonerider-motorcycle.es/cdn/shop/collections/R1250GS.jpg?v=1732110805"
  },
  {
    marca: "Harley-Davidson",
    modelo: "Iron 883",
    año: 2020,
    cilindrada: 883,
    color: "Negro",
    tipo: "cruiser",
    potencia: 49,
    peso: 256,
    transmision: "manual",
    precio: 9000,
    disponible: true,
    combustible: "gasolina",
    consumo: 6.8,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 12.5,
    numeroMarchas: 5,
    alturaAsiento: 76,
    fechaIngreso: new Date("2022-11-05"),
    descripcion: "Clásica cruiser con estilo y potencia para ciudad.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ-VE66zgTg0XVC6zPoI5rp-xXH2LaeZhNiA&s"
  },
  {
    marca: "Triumph",
    modelo: "Bonneville T120",
    año: 2019,
    cilindrada: 1200,
    color: "Plateado",
    tipo: "classic",
    potencia: 79,
    peso: 224,
    transmision: "manual",
    precio: 12000,
    disponible: false,
    combustible: "gasolina",
    consumo: 5.9,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 14.5,
    numeroMarchas: 6,
    alturaAsiento: 79,
    fechaIngreso: new Date("2022-07-18"),
    descripcion: "Estilo clásico y rendimiento fiable.",
    imagenUrl: "https://media.triumphmotorcycles.co.uk/image/upload/f_auto/q_auto:eco/sitecoremedialibrary/media-library/images/motorcycles/modern-classics/my25/my25%20colours/du4%20bonneville%20t120/web/537/bonneville_t120_my25_cranberry_red_rhs_537px.jpeg"
  },
  {
    marca: "KTM",
    modelo: "Duke 690",
    año: 2021,
    cilindrada: 690,
    color: "Naranja",
    tipo: "naked",
    potencia: 73,
    peso: 172,
    transmision: "manual",
    precio: 8600,
    disponible: true,
    combustible: "gasolina",
    consumo: 4.5,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 13.5,
    numeroMarchas: 6,
    alturaAsiento: 83,
    fechaIngreso: new Date("2023-03-25"),
    descripcion: "Naked ligera y potente para ciudad.",
    imagenUrl: "https://raceline.com.co/cdn/shop/files/KTM_690_DUKE_R_m.jpg?v=1705419510"
  },
  {
    marca: "Honda",
    modelo: "Africa Twin",
    año: 2022,
    cilindrada: 1084,
    color: "Rojo",
    tipo: "adventure",
    potencia: 101,
    peso: 226,
    transmision: "manual",
    precio: 14000,
    disponible: true,
    combustible: "gasolina",
    consumo: 5.3,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 18.8,
    numeroMarchas: 6,
    alturaAsiento: 87,
    fechaIngreso: new Date("2023-05-20"),
    descripcion: "Perfecta para viajes largos y terrenos difíciles.",
    imagenUrl: "https://motos.honda.com.co/images/cms/Africa-Twin-Adventure-Sports-blanca.png"
  },
  {
    marca: "Yamaha",
    modelo: "Tenere 700",
    año: 2021,
    cilindrada: 689,
    color: "Blanco",
    tipo: "adventure",
    potencia: 72,
    peso: 204,
    transmision: "manual",
    precio: 9999,
    disponible: true,
    combustible: "gasolina",
    consumo: 4.9,
    sistemaFrenos: "ABS, discos delanteros y traseros",
    capacidadTanque: 16,
    numeroMarchas: 6,
    alturaAsiento: 87,
    fechaIngreso: new Date("2023-02-01"),
    descripcion: "Aventura y manejo en todo tipo de caminos.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTns99aNyNgs5jqA83Du-YqaUxZnpW0JhI5mQ&s"
  },
  {
    marca: "Zero Motorcycles",
    modelo: "SR/F",
    año: 2022,
    cilindrada: 0,
    color: "Negro",
    tipo: "naked",
    potencia: 110,
    peso: 220,
    transmision: "automática",
    precio: 19999,
    disponible: true,
    combustible: "eléctrico",
    autonomia: 259,
    consumo: 0,
    sistemaFrenos: "ABS, frenos de disco",
    capacidadTanque: 0,
    numeroMarchas: 1,
    alturaAsiento: 79,
    fechaIngreso: new Date("2023-03-15"),
    descripcion: "Moto eléctrica con gran torque instantáneo y sin emisiones.",
    imagenUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs2HAikvkd0U4BLyGBduSjrq1tlZ9EsXUuww&s"
  },
  {
    marca: "Vespa",
    modelo: "GTS 300",
    año: 2020,
    cilindrada: 278,
    color: "Blanco",
    tipo: "scooter",
    potencia: 23,
    peso: 160,
    transmision: "automática",
    precio: 6000,
    disponible: true,
    combustible: "gasolina",
    consumo: 3.5,
    sistemaFrenos: "ABS, discos delanteros",
    capacidadTanque: 8,
    numeroMarchas: 0,
    alturaAsiento: 79,
    fechaIngreso: new Date("2022-09-01"),
    descripcion: "Scooter elegante y práctica para ciudad.",
    imagenUrl: "https://motomall.com.co/wp-content/uploads/2023/01/vento-gts-300-nuevocomprar.jpg"
  }
];
